FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y \
    build-essential \
    cmake \
    python3-dev \
    vim \
    zsh \
    tmux \
    openjdk-8-jdk \
    git \
    wget \
    unzip \
&& apt-get clean all

ENV HOME /home/dm035947

RUN groupdel users                                              \
  && groupadd -r dm035947                                       \
  && useradd --create-home --home-dir $HOME                     \
             -r -g dm035947                                     \
             dm035947

USER devyn

RUN mkdir -p $HOME/.vim/pack/my-plugins/start/ && \
    cd $HOME/.vim/pack/my-plugins/start && \
    git clone https://github.com/ycm-core/YouCompleteMe && \
    cd ./YouCompleteMe && \
    git submodule update --init --recursive && \
    python3 install.py --java-completer && \
    cd $HOME/.vim/pack/my-plugins/start && \
    git clone https://github.com/qpkorr/vim-bufkill && \
    git clone https://github.com/kien/ctrlp.vim && \
    git clone https://github.com/scrooloose/nerdtree && \
    git clone https://github.com/vim-airline/vim-airline && \
    git clone https://github.com/vim-airline/vim-airline-themes && \
    git clone https://github.com/vim-scripts/dbext.vim && \
    git clone https://github.com/Dica-Developer/vim-jdb && \
    git clone https://github.com/xolox/vim-misc && \
    git clone https://github.com/tpope/vim-dispatch && \
    git clone https://github.com/NLKNguyen/papercolor-theme

RUN sh -c "$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

RUN sed -i 's/ZSH_THEME=\"robbyrussell\"/ZSH_THEME=\"lambda\"/g' ~/.zshrc

RUN echo "set-option -g default-shell /bin/zsh" >> $HOME/.tmux.conf

RUN echo "cd ~" >> $HOME/.zshrc

RUN cd $HOME && wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip

RUN cd $HOME && unzip -d maven ./apache-maven-3.5.4-bin.zip && \
    rm ./apache-maven-3.5.4-bin.zip

ENV LANG en_us.utf-8

ENV PATH $PATH:$HOME/maven/apache-maven-3.5.4/bin/

ENTRYPOINT /usr/bin/zsh  
